In [4]:
import torch
import torch.nn as nn
import numpy as np 
import matplotlib.pyplot as plt 
import time

In [7]:
n = np.linspace(0, 1, 5)
t = torch.linspace(0, 1, 5)

In [11]:
n = np.arange(48).reshape(3,4,4)
t = torch.arange(48).reshape(3,4,4)

In [15]:
a = np.ones((6,5))
b = np.arange(5).reshape((1,5))

In [21]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
b

array([[0, 1, 2, 3, 4]])

In [23]:
a+b

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [24]:
a = torch.ones((6,5))
b = torch.arange(5).reshape((1,5))

In [25]:
a+b

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

In [26]:
Image = torch.randn((256,256,3))
Scale = torch.tensor([0.5,1.5,1])

In [27]:
Result = Image*Scale

In [28]:
Images = torch.randn((2,256,256,3))
Scales = torch.tensor([0.5,1.5,1,1.5,1,0.5]).reshape((2,1,1,3))

In [31]:
Results = Images*Scales

In [32]:
t = torch.tensor([0.5,1,3,4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(2.1250), tensor(1.6520), tensor(4.), tensor(0.5000))

In [35]:
t = torch.arange(20, dtype=float).reshape(5,4)
t, torch.mean(t, axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64))

In [39]:
t = torch.randn(5,256,256,3)
torch.mean(t,axis=0).shape

torch.Size([256, 256, 3])

In [40]:
torch.mean(t,axis=-1).shape

torch.Size([5, 256, 256])

In [43]:
values, indices = torch.max(t, axis=-1)

In [45]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)
y = x.pow(3).sum()
y

tensor(917., grad_fn=<SumBackward0>)

In [46]:
y.backward() #compute the gradient
x.grad #print the gradient (everything that has happened to x)

tensor([[ 75., 192.],
        [ 48., 108.]])

In [47]:
3*x**2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)